item { 
	id:  1
	name: "hello"
	
}
item { 
	id: 2
	name: "thanks"
}
item { 
	id: 3
	name: "please"
}
item { 
	id: 4
	name: "sorry"
}
item { 
	id: 5
	name: "yes"
}
item { 
	id: 6
	name: "no"
}
item { 
	id: 7
	name: "help"
}
